name: Flutter Unit Testing Action
on:
  push:
    branches:
      - main
      - development
      - feature/*
      - release/*
  pull_request:
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter  --version
      - name: Install packages
        run: flutter pub get
      - name: Run generator
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Run test
        run: flutter test